export const SET_PRODUCTS = "SET_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PLUS_QTY_CART = "PLUS_QTY_CART";
export const CLEAR_CART = "CLEAR_CART";

export const ADD_TO_PREVIEW = "ADD_TO_PREVIEW";
export const REMOVE_FROM_PREVIEW = "REMOVE_FROM_PREVIEW";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
